const projects = [
  {
    title: 'StorePI',
    description:
      'An open-source REST API that was created for use in e-commerce prototyping and Front-End Developer talent evaluations. Features product, user, cart, and authentication resources plus more.',
    tools: ['Node', 'Express', 'MongoDB', 'Mongoose', 'Heroku'],
    primaryCTA: 'View Docs',
    primaryLink: 'https://documenter.getpostman.com/view/12907395/UyxjF694',
    secondaryCTA: 'View Code',
    secondaryLink: 'https://github.com/alexsommers7/StorePI',
    image: require('@/assets/project-showcase--storepi.png'),
    imageWebp: require('@/assets/project-showcase--storepi.webp'),
    alt: 'StorePI documentation displayed on various devices',
    showOnHomePage: true,
  },
  {
    title: 'Vue Shop',
    description:
      'A simple ecommerce landing page that helps visualize some of the capabilities of StorePI. Features sorting, filtering, and basic cart functionality.',
    tools: ['Vue 3', 'Pinia', 'Quasar', 'StorePI', 'SCSS', 'Netlify'],
    primaryCTA: 'View Demo',
    primaryLink: 'https://vue-fake-shop.netlify.app/',
    secondaryCTA: 'View Code',
    secondaryLink: 'https://github.com/alexsommers7/vue-shop',
    image: require('@/assets/project-showcase--vue-shop.png'),
    imageWebp: require('@/assets/project-showcase--vue-shop.webp'),
    alt: 'Vue Shop website displayed on various devices',
    showOnHomePage: true,
  },
  {
    title: 'AlexSommers.com',
    description:
      "This bad boy right here! I built it as a one-stop-shop to house my work, resume, and contact information. What's more, it's a way to document my journey and share it with others.",
    tools: ['Vue.js', 'Vue Router', 'GSAP', 'SCSS', 'Netlify', 'Adobe XD'],
    primaryCTA: 'View Demo',
    primaryLink: 'https://alexsommers.com/',
    secondaryCTA: 'View Code',
    secondaryLink: 'https://github.com/alexsommers7/portfolio',
    image: require('@/assets/project-showcase--alex-sommers.png'),
    imageWebp: require('@/assets/project-showcase--alex-sommers.webp'),
    alt: 'AlexSommers.com displayed on various devices',
    showOnHomePage: false,
  },
  {
    title: 'Heritage Assisted Living',
    description:
      'A website for a local Assisted Living Facility that has since sold and rebranded. The owners were looking for a way to tell their story in a visual manner as well as help in establishing their digital footprint.',
    tools: ['JavaScript', 'SCSS', 'HTML', 'Netlify', 'Adobe XD'],
    primaryCTA: 'View Demo',
    primaryLink: 'https://heritage-az.netlify.app/',
    secondaryCTA: 'View Code',
    secondaryLink: 'https://github.com/alexsommers7/heritage-assisted-living',
    image: require('@/assets/project-showcase--heritage-assited-living.png'),
    imageWebp: require('@/assets/project-showcase--heritage-assited-living.webp'),
    alt: 'Heritage Assisted Living website displayed on various devices',
    showOnHomePage: false,
  },
  {
    title: 'Lovely Hearts AZ',
    description:
      'Website for a local in-home care provider who was looking for a way to provide a high-level overview of their services, as well as provide a method of communication for prospective customers.',
    tools: ['JavaScript', 'SCSS', 'HTML', 'Netlify', 'Adobe XD'],
    primaryCTA: 'View Demo',
    primaryLink: 'https://lovelyheartsaz.com/',
    secondaryCTA: 'View Code',
    secondaryLink: 'https://github.com/alexsommers7/lovelyheartsaz',
    image: require('@/assets/project-showcase--lovely-hearts-az.png'),
    imageWebp: require('@/assets/project-showcase--lovely-hearts-az.webp'),
    alt: 'Lovely Hearts AZ website displayed on various devices',
    showOnHomePage: true,
  },
  {
    title: 'J.A Dancik Electric',
    description:
      'My first "real world" website! This client, a local electrician, wanted to keep the information basic and simply establish a way for current and future customers to contact them.',
    tools: ['JavaScript', 'SCSS', 'HTML', 'Netlify', 'Adobe XD'],
    primaryCTA: 'View Demo',
    primaryLink: 'https://jadancikelectric.com/',
    secondaryCTA: 'View Code',
    secondaryLink: 'https://github.com/alexsommers7/ja-dancik-electric',
    image: require('@/assets/project-showcase--jad-electric.png'),
    imageWebp: require('@/assets/project-showcase--jad-electric.webp'),
    alt: 'J.A. Dancik Electric website displayed on various devices',
    showOnHomePage: false,
  },
];

export default projects;
