const tools = [
  {
    title: 'Vue.js',
    icon: require('@/assets/icons/vue.svg'),
    type: 'tech',
    alt: 'Vue JavaScript Framework',
    usingLately: true,
  },
  {
    title: 'Pinia',
    icon: require('@/assets/icons/pinia.svg'),
    type: 'tech',
    alt: 'Pinia State Management Library',
    usingLately: false,
  },
  {
    title: 'Quasar',
    icon: require('@/assets/icons/quasar.svg'),
    type: 'tech',
    alt: 'Quasar Vue Framework',
    usingLately: true,
  },
  {
    title: 'Alpine.js',
    icon: require('@/assets/icons/alpine.svg'),
    type: 'tech',
    class: 'brighten',
    alt: 'Alpine JavaScript Framework',
    usingLately: true,
  },
  {
    title: 'JavaScript',
    icon: require('@/assets/icons/javascript.svg'),
    type: 'tech',
    alt: 'JavaScript (ES6)',
    usingLately: false,
  },
  {
    title: 'SCSS',
    icon: require('@/assets/icons/sass.svg'),
    type: 'tech',
    alt: 'Sassy CSS (SCSS)',
    usingLately: false,
  },
  {
    title: 'GSAP',
    icon: require('@/assets/icons/gsap.svg'),
    type: 'tech',
    alt: 'Greensock Animation Platform (GSAP)',
    usingLately: false,
  },
  {
    title: 'Foundation',
    icon: require('@/assets/icons/zurb-foundation.svg'),
    type: 'tech',
    alt: 'Zurb Foundation CSS Framework',
    usingLately: false,
  },
  {
    title: 'Bootstrap',
    icon: require('@/assets/icons/bootstrap.svg'),
    type: 'tech',
    alt: 'Bootstrap CSS Framework',
    usingLately: false,
  },
  {
    title: 'Git',
    icon: require('@/assets/icons/git.svg'),
    type: 'tech',
    alt: 'Git Version Control',
    usingLately: false,
  },
  {
    title: 'XD',
    icon: require('@/assets/icons/xd.svg'),
    type: 'design',
    alt: 'Adobe XD',
    usingLately: false,
  },
  {
    title: 'Figma',
    icon: require('@/assets/icons/figma.svg'),
    type: 'design',
    alt: 'Figma Design Software',
    usingLately: false,
  },
  {
    title: 'Photoshop',
    icon: require('@/assets/icons/photoshop.svg'),
    type: 'design',
    alt: 'Adobe Photoshop',
    usingLately: false,
  },
  {
    title: 'Illustrator',
    icon: require('@/assets/icons/illustrator.svg'),
    type: 'design',
    alt: 'Adobe Illustrator',
    usingLately: false,
  },
  {
    title: 'Lightroom',
    icon: require('@/assets/icons/lightroom.svg'),
    type: 'design',
    alt: 'Adobe Lightroom',
    usingLately: false,
  },
];

export default tools;
